In [70]:
import numpy as np

def editDist(s1, s2):
    m = len(s1) + 1
    n = len(s2) + 1
    
    dp = np.zeros((m,n))
    
    for i in range(0,m):
        dp[i,0] = i
    for j in range(0,n):
        dp[0,j] = j
    
    for i in range(1,m):
        for j in range(1,n):
#             print(dp[i,j])
#             print(s1[i-1] + " - " + s2[j-1])

            dp[i,j] = min( dp[i-1,j-1] + 1 if s1[i-1] != s2[j-1] else dp[i-1,j-1],  
                          dp[i-1,j] + 1,
                          dp[i,j-1] + 1             
                )
#             else:
#                 dp[i,j] = min(dp[i-1,j-1],
#                               dp[i-1,j] + 1,
#                               dp[i,j-1] + 1             
#                 )
    print(dp)
    return dp[m-1,n-1]


s1 = "fast"
s2 = "cats"

print(editDist(s1,s2))

[[0. 1. 2. 3. 4.]
 [1. 1. 2. 3. 4.]
 [2. 2. 1. 2. 3.]
 [3. 3. 2. 2. 2.]
 [4. 4. 3. 2. 3.]]
3.0
