In [14]:

# Collection of documents (corpus)

review_1 = "The Glider II is a great soccer ball"
review_2 = "What a bad soccer ball"
review_3 = "I am happy with The glider"

docs = [review_1, review_2, review_3]

In [21]:
# list of terms
uniqueTerms = {term for doc in docs for term in doc.split()}
uniqueTerms = sorted(uniqueTerms)
print(uniqueTerms)

['Glider', 'I', 'II', 'The', 'What', 'a', 'am', 'bad', 'ball', 'glider', 'great', 'happy', 'is', 'soccer', 'with']


In [22]:
#constructing document-term Matrix

docTermM = {}

for term in uniqueTerms:
    docTermM[term] = []
    
    for doc in docs:
        if term in doc:
            docTermM[term].append(1)
        else:
            docTermM[term].append(0)
            
docTermM

{'Glider': [1, 0, 0],
 'I': [1, 0, 1],
 'II': [1, 0, 0],
 'The': [1, 0, 1],
 'What': [0, 1, 0],
 'a': [1, 1, 1],
 'am': [0, 0, 1],
 'bad': [0, 1, 0],
 'ball': [1, 1, 0],
 'glider': [0, 0, 1],
 'great': [1, 0, 0],
 'happy': [0, 0, 1],
 'is': [1, 0, 0],
 'soccer': [1, 1, 0],
 'with': [0, 0, 1]}

In [29]:
# Boolean queries
import numpy as np

v1= np.array(docTermM['Glider'])
v2 = np.array(docTermM['soccer'])

print(v1)
print(v2)
print("Glider AND soccer")
v3 = v1 & v2
print(v3)
[doc for doc in v3*docArray if doc]


[1 0 0]
[1 1 0]
Glider AND soccer
[1 0 0]


['The Glider II is a great soccer ball']

In [30]:


print("Glider OR soccer")
v3 = v1 | v2
print(v3)
[doc for doc in v3*docArray if doc]

Glider OR soccer
[1 1 0]


['The Glider II is a great soccer ball', 'What a bad soccer ball']